### ISSUE TITLE
Feature Requests ...

### ISSUE THREAD

**Issue by mp3monster** [oracle/oci-designer-toolkit#196]
Some suggestions for features ....

- Externalize the key information  so you can swap between different OCI instances
- As the solution is a Python app, it should be able to run on Windows natively if the HTTP server could be more platform agnostic.
- able to design using OKit without needing a tenancy - some organizations control who can have the policies and means to upload key files.

**Comment by toxophilist** [comment]
@mp3monster 

1. It is currently not recommended to run on an OCI instance although the Installation guide does document native installation it is accessed via SSH Tunnel. We are looking at add Authentication for OCI instances but currently have no date for this.
2. The backend server is simply Flask / GUnicorn with no specific linux implementation there is no reason it could not be installed natively on Windows / Mac if the OS supports the appropriate versions of the modules used. Oracle Linux is used simply because we do not need to worry about the license. Ultimately I plan on having an image on the Oracle Docker Hub for download
3. OKIT was designed to run locally on a laptop hence the Docker/Vagrant Containers and be agnostic of the destination tenancy / compartment and simply allow you to generate the Terraform / Ansible code that can be run against any Tenancy / Compartment specified by the Terraform plan/apply or Ansible playbook commands.

**Comment by mp3monster** [comment]
@toxophilist thanks for the feedback.  By externalizing the configuration I was thinking about the fact that I may want to switch between several tenancies (as ACED and a consultant I need to switch between at least 3 tenancies), but because the configuration is wrapped in Docker it would require several distinct instances. Rather than perhaps providing the details from outside docker image via a mount point. Another option is to provide the details via a UI

Regarding gunicorn, the documentation I read on the gunicorn site  pointed to it being a Linux solution.

Docker/Vagrant containers as platform agnostic.  I see that but I think that the issue reported on the build is a OS line termination issue -  https://blog.mp3monster.org/2020/12/08/okit-oci-design-on-windows/  

The only downside of the approach is that if you're working in a reasonably strict environment software approval processes will be very resistant.  Fortunately, I have reasonable local privileges but tech spec the laptop is pretty tame in terms of spec - so installing and running Docker does eat into limited resources.

**Comment by toxophilist** [comment]
@mp3monster The first can be solved by having multiple sections in the config file that is mounted through during the run command. I have a config section for each of the tenancies I need to access and can choose the appropriate one during Query / Export to RM.

**Comment by toxophilist** [comment]
Added to OCD [Release](https://github.com/oracle/oci-designer-toolkit/releases)
