### ISSUE TITLE
Does OKIT support GovCloud Regions

### ISSUE THREAD

**Issue by codersteinersky** [oracle/oci-designer-toolkit#379]
It doesn't seem OKIT supports US IL5 or other GovCloud regions at least for a query.  Is that actually supported in some way and I'm missing it?  If it isn't currently supported can that be easily added?  Thanks, JD

**Comment by toxophilist** [comment]
@codersteinersky There is nothing with OKIT to stop this but they are no displayed by default. The region list is built just prior to release by querying OCI. I do not have access to Gov regions hence only the public regions are added to the dropdown.json file. Now when you refresh/access the page OKIT will try to update its dropdown.json by querying the 'DEFAULT' connection. If you DEFAULT points to the Gov region you should see it appear in your list.

Having said that I'm looking to improve the way I query / update the dropdown.json to resolve the current issues.

**Comment by codersteinersky** [comment]
Thank you so much.  That simple workaround will be great in the mean time.

**Comment by toxophilist** [comment]
@codersteinersky I've pushed a change to the nightly branch which switches Regions / Dropdown data based on the selected Config Profile. Could you possibly clone this branch and let me know if switching to your Gov config profile displays the Gov Regions. Sorry I can't test because I don't have access to the Gov regions.

**Comment by toxophilist** [comment]
@codersteinersky if you select your connection profile within v0.24.0 on the toolbar you should see the region list updated.
