### ISSUE TITLE
Error executing: docker-compose up

### ISSUE THREAD

**Issue by jjciudad** [oracle/oci-designer-toolkit#45]
I am trying to install OCI designer toolkit, I am trying it in an OCI Ubuntu instance. I have followed all the steps indicated in the installation guide, but in the following: docker-compose up
I get the following error:

https://yum.oracle.com/repo/OracleLinux/OL7/oci/included/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
.
.
.
failure: repodata/repomd.xml from ol7_ociyum_config: [Errno 256] No more mirrors to try.
https://yum.oracle.com/repo/OracleLinux/OL7/oci/included/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
ERROR: Service 'okit' failed to build

Could you tell me how to continue?

Thanks and regards.

**Comment by webfrasse** [comment]
It's not a good idea to install OKIT on an OCI instance since you have to put your private keys on that instance in the cloud. If that instance gets compromised you have given away the main key to your tenancy. That's especially bad if it's a customer tenancy. OKIT is intended to be installed on your personal computer where you're in control of your private keys. We have a roadmap for running OKIT in the cloud but we're not there yet just because it can't be done securely yet.

**Comment by toxophilist** [comment]
@jjciudad This is an issue with OCI not OKIT see [Issue #38](https://github.com/oracle/oci-designer-toolkit/issues/38)

**Comment by jjciudad** [comment]
Thanks webfrasse, toxophilist.
Today I tried to install on my laptop (Win10), for this I had to install docker for windows. I'm at the same point as yesterday, but now the error when executing "docker-compose up" is as follows:

ERROR: for c7227a46e147_okit  Cannot start service okit: Ports are not available: listen tcp 0.0.0.0:80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

ERROR: for okit  Cannot start service okit: Ports are not available: listen tcp 0.0.0.0:80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
ERROR: Encountered errors while bringing up the project.

I would appreciate your help.

Thanks and regards.

**Comment by webfrasse** [comment]
I donät have access to a windows env. but generally ports below 1024 will trigger a warning since they are considered privileged. I get a warning on my mac from vagrant for that reason. Another reason for this error could be the windows firewall or McAfee.

Maybe someone with a windows env. can add some insight to this issue?

**Comment by rastangineer** [comment]
Maybe you have something running on port 80 on your windows machine. I was able to install OKIT using docker image, I received the warning about ports below 1024, but the OKIT started fine.

**Comment by toxophilist** [comment]
@jjciudad Have you tried this with the latest release

**Comment by toxophilist** [comment]
This is an issues accessing the oracle yum repo from the box executing docker and associated with the yum update command in the docker file. To validate your system create a simple docker container based on the oraclelinux:7-slim image and connect then execute yum update.

If this works can you try the latest OKIT release and if you still see the issue with yum reopen this issue.
